### ISSUE TITLE
Incorrect viability categories in 2019/2020 KRN and PIX Comparison across years graphs

### ISSUE THREAD

**Issue by rebeca-becdach** [tyburns/WHAPDataAnalysis#12]
Kern 2019 should only have four values in the good category. Pixley 2020 should have no values in the very good category

**Comment by emilioalaca** [comment]
Are the yield values or the class ranges incorrect? I used the definitions in WHAP_Viability_20210610.csv, which are:
  Species class       KRN   PIX   SAC   CLS   SLW   MDC class_color
  <chr>   <ord>     <int> <int> <int> <int> <int> <int> <chr>      
1 st_g_m2 Poor          0     0     0     0     0     0 red        
2 st_g_m2 Fair         85    85    50    50    50    50 yellow     
3 st_g_m2 Good        180   180   100   100   100   100 chartreuse 
4 st_g_m2 Very_Good   300   300   200   200   200   200 chartreuse3

Let me know where the error is.

**Comment by rebeca-becdach** [comment]
The class ranges are correct on that file

**Comment by emilioalaca** [comment]
Are the calculated yields incorrect, then? The current figure uses those ranges.

BTW, we should change the colors to shades of grey or something that all people can distinguish.

**Comment by rebeca-becdach** [comment]
I updated the class ranges file last week (it was incorrect before) and re-ran the code but got the same result as before. Can you try rerunning the code?

**Comment by emilioalaca** [comment]
RB and EAL agreed that the current CompareYears.Rmd is producing the correct graphs. The problem is that the current report for 2020 in the Output2020 folder was created before we decided to have different ranges for different refuges. The ranges (boundaries) for 2020 are hard coded in the MainScript for 2020. That script has to be modified if we want to apply the new boundaries to 2020, and probably the same has to be done for 2019. I think that this has low priority for me but will reconsider depending on what Kara needs. RB received some general suggestions on how to  modify WHAPMainScript2020-21.Rmd to fix this.

For figures showing 2019 and 2020 results based on CompareYears.Rmd RB will create a similar CompareYears_2019_2020.Rmd for the 2020 report.

I will leave the issue open until all code uses the same (latest) viability classes.

**Comment by emilioalaca** [comment]
Just following up
