### ISSUE TITLE
qdt_mass_g_m2_2021.txt has "Shrew Slough" as a subunit

### ISSUE THREAD

**Issue by rebeca-becdach** [tyburns/WHAPDataAnalysis#16]
The text file needs to be updated with data with the edits Eric made to correct the error that led to the shrew slough units being included.

**Comment by emilioalaca** [comment]
I do not see Shrew Slough in the current data files. Please, check again and if you find it, specify the file name and lines where Shrew slough is found.

Otherwise, close the issue.

**Comment by rebeca-becdach** [comment]
Shrew Slew is still on qdt_mass_g_m2_2021.txt. I am not sure where the data on that text file comes from

**Comment by emilioalaca** [comment]
qdt_mass_g_m2_2021.txt is an output file that resulted from running the scripts on the old data. We have not run the script again since the data were corrected. The output files will remain incorrect until we manage to re-run the scripts with correct data or delete them. I have not been able to run the script again because I think there are still unresolved issues in the data. See the new data issue.
